import Link from "next/link";

export const metadata = {
  title: "Privacy & Terms — AI-gency",
  description: "Privacy Policy and Terms of Service for AI-gency Travel Planner.",
};

export default function LegalPage() {
  return (
    <div className="min-h-screen" style={{ background: "#FFF8F0" }}>
      <div className="max-w-2xl mx-auto px-4 sm:px-6 pt-8 pb-16 space-y-6">

        {/* Header */}
        <div>
          <Link href="/" className="inline-flex items-center gap-1.5 text-xs font-black text-orange-400 hover:text-orange-600 transition-colors mb-4">
            ← Back to Home
          </Link>
          <p className="text-xs font-black text-orange-400 uppercase tracking-widest mb-1">✦ Legal</p>
          <h1 className="text-3xl font-black text-gray-900">Privacy &amp; Terms</h1>
          <p className="text-sm text-gray-400 mt-1">Last updated: March 2025</p>
        </div>

        {/* Privacy Policy */}
        <div className="bg-white rounded-3xl border border-orange-100 p-6 shadow-sm space-y-4">
          <h2 className="text-xl font-black text-gray-900 flex items-center gap-2">
            <span className="text-2xl">🔒</span> Privacy Policy
          </h2>

          <div className="space-y-3 text-sm text-gray-600 leading-relaxed">
            <div>
              <h3 className="font-black text-gray-800 mb-1">Data Storage</h3>
              <p>AI-gency stores all your trip data exclusively in your browser&apos;s <strong>localStorage</strong>. No trip plans, itineraries, or personal information are ever sent to or stored on our servers. Your data lives only on your device and is fully under your control.</p>
            </div>

            <div>
              <h3 className="font-black text-gray-800 mb-1">AI Processing</h3>
              <p>Trip planning requests are processed by <strong>Claude AI</strong> (Anthropic). When you generate a trip, your destination, dates, and budget are sent to Anthropic&apos;s API to produce your itinerary. Please review <a href="https://www.anthropic.com/privacy" target="_blank" rel="noopener noreferrer" className="text-orange-500 font-bold hover:underline">Anthropic&apos;s Privacy Policy</a> for details on how they handle data.</p>
            </div>

            <div>
              <h3 className="font-black text-gray-800 mb-1">Weather Data</h3>
              <p>Weather information is fetched from <strong>Open-Meteo</strong>, a free and open-source weather API. Your destination coordinates are shared with Open-Meteo to retrieve forecasts. No personal identifiers are included in these requests.</p>
            </div>

            <div>
              <h3 className="font-black text-gray-800 mb-1">Booking &amp; Affiliate Links</h3>
              <p>Some links to hotels, flights, and experiences may be affiliate links through services such as Travelpayouts or Booking.com. Clicking these links may earn AI-gency a small commission at no extra cost to you. These third-party services have their own privacy policies.</p>
            </div>

            <div>
              <h3 className="font-black text-gray-800 mb-1">No Account Required</h3>
              <p>AI-gency does not collect email addresses, passwords, or any account information. There is no registration process. We do not use cookies for tracking or analytics.</p>
            </div>
          </div>
        </div>

        {/* Terms of Service */}
        <div className="bg-white rounded-3xl border border-orange-100 p-6 shadow-sm space-y-4">
          <h2 className="text-xl font-black text-gray-900 flex items-center gap-2">
            <span className="text-2xl">📋</span> Terms of Service
          </h2>

          <div className="space-y-3 text-sm text-gray-600 leading-relaxed">
            <div>
              <h3 className="font-black text-gray-800 mb-1">Personal Use</h3>
              <p>AI-gency is intended for personal travel planning purposes only. You may not use the app for commercial resale, automated scraping, or any unlawful activity.</p>
            </div>

            <div>
              <h3 className="font-black text-gray-800 mb-1">AI-Generated Content</h3>
              <p>Trip itineraries, budget estimates, and suggestions are generated by artificial intelligence and are provided for informational purposes only. <strong>AI suggestions are not guaranteed to be accurate, current, or complete.</strong> Always verify prices, availability, and travel requirements independently before booking.</p>
            </div>

            <div>
              <h3 className="font-black text-gray-800 mb-1">Third-Party Services</h3>
              <p>AI-gency may display links to third-party booking platforms, transportation providers, and attractions. <strong>Your use of third-party services is entirely your own responsibility.</strong> We are not liable for any transactions, disputes, or issues arising from third-party services.</p>
            </div>

            <div>
              <h3 className="font-black text-gray-800 mb-1">No Warranty</h3>
              <p>AI-gency is provided &quot;as is&quot; without any warranties of any kind. We do not guarantee continuous, uninterrupted, or error-free access to the app or its features.</p>
            </div>

            <div>
              <h3 className="font-black text-gray-800 mb-1">Changes</h3>
              <p>We may update these terms and privacy policy from time to time. Continued use of AI-gency after any changes constitutes acceptance of the updated terms.</p>
            </div>
          </div>
        </div>

        {/* Contact */}
        <div className="rounded-2xl p-5 text-center" style={{ background: "linear-gradient(135deg,#f97316,#ec4899)" }}>
          <p className="text-white font-black mb-1">Questions?</p>
          <p className="text-white/80 text-sm">AI-gency is a personal travel planning tool. For any concerns, use the feedback option in the app.</p>
        </div>

      </div>
    </div>
  );
}
